UserList/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("UserListApp/", include("UserListApp.urls")),
    path('admin/', admin.site.urls),
]

UserListApp/urls.py
from django.urls import path

from . import views

app_name = "UserListApp"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
]

UserListApp/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user = models.CharField(max_length=250)
    pub_date = models.DateTimeField("Date published")

    def __str__(self):
        return self.user

UserListApp/views.py
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader

from .models import User

# Create your views here.
def index(request):
    user_list = User.objects.order_by("-pub_date")
    context = {
        "user_list" : user_list
    }
    return render(request, "UserListApp/index.html", context)

def add(request):
    try:
        # On the first time this page loads, the request is not a POST
        # and we get an exception
        new_user = User(user=request.POST["username"], pub_date=timezone.now())
    except Exception as e:
        # Redisplay the question voting form.
        return render(
            request,
            "UserListApp/add.html",
            {
                "error_message": str(e),
            },
        )
    else:
        new_user.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("UserListApp:index", args=()))

UserListApp/templates/UserListApp/add.html
<form action="{% url 'UserListApp:add' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add username form</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label>Username:</label><br>
            <input type="text" name="username"/>
            <input type="submit" value="add">
    </fieldset>
    <a href=".."> Return to user list</a>
    </form>

UserListApp/templates/UserListApp/index.html
<html>
    <head>
    </head>
    <body>
        {% if user_list %}
            <table>
                <tr>
                    <th align="left">Username</th>
                    <th align="left">Creation Date</th>
                </tr>
                {% for user in user_list %}
                    <tr><td width="400 px">{{ user.user }}</td><td>{{ user.pub_date }}</td></tr>
                {% endfor %}
            </table>
        {% else %}
            <p>No users created</p>
        {% endif %}
        <br/>
        <a href="add"> Add user </a>
    </body>
</html>